services:
  k6:
    image: grafana/k6
    volumes:
      - ./src/k6/:/app
    command:
      - 'run'
      - '/app/script.ts'
    env_file:
      - path: ./.env
        required: false
  traefik:
    image: "traefik:v3.3"
    # ports:
    #   - "8086:8080"
    volumes:
      - ./docker/traefik/static:/etc/traefik
      - ./docker/traefik/dynamic:/config/dynamic
      - ./data/traefik-log:/var/log/traefik
  echo:
    image: mendhak/http-https-echo:36
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    depends_on:
      - traefik
    environment:
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
      DISABLE_PARSERS: crowdsecurity/whitelists
    volumes:
      - ./docker/crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - ./data/crowdsec/data:/var/lib/crowdsec/data
      - ./data/traefik-log:/var/log/traefik
  goeffel:
    image: foxxmd/goeffel:edge
    # required for goeffel to share PID address space with host
    pid: host
    # required for goeffel to have permission to access PIDs
    cap_add:
      - CAP_SYS_PTRACE
    volumes:
      - "./data/goeffel:/app"
    # you want to override this
    command:
      - 'goeffel'
      - '-h'
